// `script` driver — for scenarios whose load is generated by a standalone
// Node script (fanout-bench.js, etc.) rather than artillery. Flow:
//
//   1. ensureAppDeps  → meteor npm ci if the app's node_modules is missing
//   2. resetMeteorApp → meteor reset to start from a known state
//   3. prepareGcOutput → carve a temp file path that the gc-monitor
//      (--require'd into the Meteor process) will write to on SIGTERM
//   4. startMeteorApp → spawn `meteor run`, returns { proc, getRuntimeInfo }
//   5. waitForApp → poll the port until the app answers 2xx
//   6. startCollectors → spawn process-monitor for APP + DB pids
//   7. Run the script via execFileSync (5-min timeout so a hung script
//      can't lock the harness forever)
//   8. Parse the LAST line of stdout as JSON — convention: scripts dump
//      one summary JSON line at the end. Earlier lines (logs) are ignored.
//   9. stopCollectors → SIGTERM the monitors, drain stdout, parse
//   10. stopMeteorApp → SIGTERM Meteor, give it 3s to flush GC monitor
//   11. drainPostStopGc → pick up the GC file if it arrived during shutdown
//   12. Build + return the result; caller writes to disk.

import path from 'node:path';
import { io } from '../runner/_io.js';
import {
  ensureAppDeps,
  resetMeteorApp,
  startMeteorApp,
  stopMeteorApp,
} from '../runner/meteor-process.js';
import { waitForApp } from '../runner/wait-for-app.js';
import {
  prepareGcOutput,
  prepareMethodTimingOutput,
  prepareSubTimingOutput,
  preparePropagationTimingOutput,
  prepareObserverPoolOutput,
  prepareDdpMessageOutput,
  prepareFrameSizeOutput,
  prepareCompressionOutput,
  prepareDriverFallbackOutput,
  startCollectors,
  stopCollectors,
} from '../runner/collectors.js';
import { buildResult } from '../reporters/json-reporter.js';
import type { MetricName } from '../reporters/json-reporter.js';
import type { DriverInputs, ScriptScenario } from '../lib/benchmark-types.js';
import { errorMessage } from '../lib/benchmark-types.js';

const HERE = import.meta.dirname;
const SCRIPT_TIMEOUT_MS = 300_000;

function parseMetrics(value: unknown): Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : {};
}

/** Executes a standalone emitted workload and merges its guarded metrics. */
export async function runScriptDriver({ scenario, scenarioName, app, appName, source, env, tag, config, scriptArgs: extraScriptArgs = [] }: DriverInputs & Readonly<{ scenario: ScriptScenario }>): Promise<ReturnType<typeof buildResult>> {
  const metricName: MetricName = scenario.metric === undefined || scenario.metric === 'fanout'
    ? 'fanout'
    : (() => { throw new TypeError(`Unsupported script metric: ${scenario.metric}`); })();
  const configuredBenchMongoUri = env.BENCH_MONGO_URL || process.env.BENCH_MONGO_URL;
  const configuredMeteorMongoUri = env.MONGO_URL || process.env.MONGO_URL;
  const fallbackMongoUri = `mongodb://127.0.0.1:${config.appPort + 1}/meteor`;
  const mongoUri = configuredBenchMongoUri
    || configuredMeteorMongoUri
    || fallbackMongoUri;
  const meteorEnv = configuredBenchMongoUri && !configuredMeteorMongoUri
    ? { ...env, MONGO_URL: mongoUri }
    : env;

  ensureAppDeps(source, app.path);
  resetMeteorApp(source, app.path);

  const { gcMonitorPath, gcOutputPath } = prepareGcOutput(tag);
  const methodTimingPath = prepareMethodTimingOutput(tag);
  const subTimingPath = prepareSubTimingOutput(tag);
  const propagationTimingPath = preparePropagationTimingOutput(tag);
  const observerPoolPath = prepareObserverPoolOutput(tag);
  const ddpMessagePath = prepareDdpMessageOutput(tag);
  const frameSizePath = prepareFrameSizeOutput(tag);
  const compressionPath = prepareCompressionOutput(tag);
  const driverFallbackPath = prepareDriverFallbackOutput(tag);

  console.log('Starting Meteor app...');
  const { proc: meteorProc, getRuntimeInfo } = startMeteorApp({
    source, appPath: app.path, port: config.appPort, env: meteorEnv, gcMonitorPath, gcOutputPath, methodTimingPath, subTimingPath, propagationTimingPath, observerPoolPath, ddpMessagePath, frameSizePath, compressionPath, driverFallbackPath,
  });

  let collectors = null;
  let lifecycleComplete = false;
  try {
    console.log('Waiting for app to start...');
    await waitForApp(config.appPort);
    console.log('App started.');

    collectors = await startCollectors({ appName, mongoUri, gcOutputPath, methodTimingPath, subTimingPath, propagationTimingPath, observerPoolPath, ddpMessagePath, frameSizePath, compressionPath, driverFallbackPath });

  const scriptPath = path.resolve(HERE, '..', scenario.script);
  const scriptArgs = [...(scenario.args || '').split(/\s+/).filter(Boolean), ...extraScriptArgs];
  console.log(`\nRunning: node ${scenario.script} ${scriptArgs.join(' ')}\n`);

  const scriptStart = Date.now();
  let scriptOutput = '';
  try {
    scriptOutput = io.execFileSync('node', [scriptPath, ...scriptArgs], {
      cwd: path.resolve(HERE, '..'),
      encoding: 'utf8',
      env: {
        ...process.env,
        ...meteorEnv,
        REMOTE_URL: `http://127.0.0.1:${config.appPort}`,
        BENCH_MONGO_URL: mongoUri,
      },
      stdio: ['ignore', 'pipe', 'pipe'],
      timeout: SCRIPT_TIMEOUT_MS,
    });
  } catch (err) {
    const stderr = typeof err === 'object' && err !== null && 'stderr' in err ? err.stderr : undefined;
    const stdout = typeof err === 'object' && err !== null && 'stdout' in err ? err.stdout : undefined;
    console.error('Script failed:', stderr || errorMessage(err));
    scriptOutput = stdout ? String(stdout) : '';
  }
  const wallClockMs = Date.now() - scriptStart;

  // Convention: scripts emit human-readable logs throughout and one final
  // JSON summary line at the end. We grab `.pop()` after split('\n') to
  // get that line. If it fails to parse we keep scriptMetrics = {} so the
  // result JSON still has the right shape (with `fanout` metric just empty).
  let scriptMetrics: Record<string, unknown> = {};
  const jsonLine = scriptOutput.trim().split('\n').pop();
  if (jsonLine) {
    try {
      scriptMetrics = parseMetrics(JSON.parse(jsonLine));
    } catch (err) {
      console.error(`Could not parse script metrics JSON from last stdout line: ${errorMessage(err)}. Last line was: ${jsonLine.slice(0, 200)}`);
    }
  }
  const collectorResults = await stopCollectors(collectors);
  await stopMeteorApp(meteorProc);
  collectorResults.push(...await stopCollectors({ ...collectors, procs: [] }));
  collectorResults.push({ metric: metricName, ...scriptMetrics });
  lifecycleComplete = true;

  if (typeof scriptMetrics.fanout_avg_ms === 'number') {
    console.log(`Fanout: avg=${scriptMetrics.fanout_avg_ms}ms p50=${scriptMetrics.fanout_p50_ms}ms p95=${scriptMetrics.fanout_p95_ms}ms max=${scriptMetrics.fanout_max_ms}ms`);
  }

  const result = buildResult({
    scenario: scenarioName,
    app: appName,
    tag,
    meteor: { version: source.version, sha: source.sha },
    runtime: getRuntimeInfo(),
    collectorResults,
    wallClockMs,
  });
  if (scenario.strict && Object.keys(scriptMetrics).length === 0) {
    throw new Error(`Strict script scenario "${scenarioName}" produced no metrics`);
  }
    return result;
  } finally {
    if (!lifecycleComplete) {
      if (collectors) {
        try {
          await stopCollectors(collectors);
        } catch (error) {
          console.error(`Could not stop collectors after driver failure: ${errorMessage(error)}`);
        }
      }
      await stopMeteorApp(meteorProc);
    }
  }
}
